import type { Metadata } from "next";
import "./globals.css";

export default function Home() {
  return (
    <div className="min-h-screen bg-red-500 text-white p-10 text-3xl font-black">
      TAILWIND ON (v4)
    </div>
  );
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//
